version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aemtli
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: ./api
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ICS_START_TIME: ${ICS_START_TIME}
    ports:
      - "4000:4000"
    depends_on:
      - db

  web:
    build: ./web
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:4000
      ADMIN_USERNAMES: ${ADMIN_USERNAMES}
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  db_data:
